name: cs221Project
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pip
  - python=3.6
  - pandas
  - scikit-learn
  - nltk
  - bottleneck
  - pillow
  - opencv
  - keras
  - h5py
  - scipy